apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app-deployment
  labels:
    app: trend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trend-app
  template:
    metadata:
      labels:
        app: trend-app
    spec:
      containers:
      - name: trend-app-container
        image: mythili121/trend-app:latest 
        ports:
        - containerPort: 80
